"""add user_personas table and conversations.user_persona_id

Revision ID: 24361230c945
Revises: 55312e3dd9b9
Create Date: 2026-06-16 17:24:23.875242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24361230c945'
down_revision: Union[str, None] = '55312e3dd9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_range', sa.String(length=10), nullable=True),
    sa.Column('personality_type', sa.String(length=4), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_style', sa.String(length=20), nullable=False),
    sa.Column('avoid_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('conversations', sa.Column('user_persona_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversations', 'user_personas', ['user_persona_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'user_persona_id')
    op.drop_table('user_personas')
    # ### end Alembic commands ###
