"""add user_profiles, conversation_profiles, relationships tables; extend personas

Revision ID: 55312e3dd9b9
Revises: 6028c1b37f18
Create Date: 2026-06-15 23:35:43.215002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55312e3dd9b9'
down_revision: Union[str, None] = '6028c1b37f18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_range', sa.String(length=10), nullable=True),
    sa.Column('personality_type', sa.String(length=4), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_style', sa.String(length=20), nullable=True),
    sa.Column('avoid_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('goal', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('conversation_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role_override', sa.String(length=50), nullable=True),
    sa.Column('tone_preference', sa.String(length=20), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('intimacy_score', sa.Float(), nullable=False),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('deep_talk_count', sa.Integer(), nullable=False),
    sa.Column('first_interaction', sa.DateTime(), nullable=False),
    sa.Column('last_interaction', sa.DateTime(), nullable=False),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'persona_id', 'conversation_id', name='uq_relationship_user_persona_conv')
    )
    op.create_index('ix_relationship_user_persona', 'relationships', ['user_id', 'persona_id'], unique=False)
    op.add_column('personas', sa.Column('backstory', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('backstory_short', sa.String(length=80), nullable=True))
    op.add_column('personas', sa.Column('mbti', sa.String(length=4), nullable=True))
    op.add_column('personas', sa.Column('speech_style', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('quirks', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('personas', sa.Column('mood_spectrum', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personas', 'mood_spectrum')
    op.drop_column('personas', 'quirks')
    op.drop_column('personas', 'speech_style')
    op.drop_column('personas', 'mbti')
    op.drop_column('personas', 'backstory_short')
    op.drop_column('personas', 'backstory')
    op.drop_index('ix_relationship_user_persona', table_name='relationships')
    op.drop_table('relationships')
    op.drop_table('conversation_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
