"""add extraction_count to conversations

Revision ID: 6028c1b37f18
Revises: 3d70bf61cc22
Create Date: 2026-06-15 17:21:56.222081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6028c1b37f18'
down_revision: Union[str, None] = '3d70bf61cc22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('conversations', sa.Column('extraction_count', sa.Integer(), nullable=True))
    op.execute("UPDATE conversations SET extraction_count = 0 WHERE extraction_count IS NULL")
    op.alter_column('conversations', 'extraction_count', nullable=False, server_default='0')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'extraction_count')
    # ### end Alembic commands ###
